version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

commands:
  install_deps:
    description: Install dependencies
    steps:
      - run:
          name: Install dependencies
          command: npm install

jobs:
  security-scans:
    resource_class: small
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - install_deps
      - prodsec/security_scans:
          mode: auto
          release-branch: master
          open-source-additional-arguments: --exclude=test
          iac-scan: disabled

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: os-team-managed-alerts
          filters:
            branches:
              ignore:
                - master

      - security-scans:
          name: Security Scans
          context:
            - open_source-managed
            - nodejs-install
